### ISSUE TITLE
lazyload should be a boolean attribute

### ISSUE THREAD

**Issue by therealadityashankar** [colscott/a-wc-router#5]
see https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes#Boolean_Attributes , basically boolean attributes don't require "true" and "false"

**Comment by colscott** [comment]
Agreed. At the time of writing that I was planning for three values rather than a boolean (eager, prefetch, lazy). But I was able to make the eager load is smart enough to wait until the page has finished loading and the user can interact with the page before it start to eager load the next pages. So using the eager load should make your web page more responsive when the user clicks the next link.
Best time to use lazy load is when a link might load a large web component.

Not sure I can change it right now though without a breaking change. Maybe I could create a lazy-load attribute and support the old lazyload="true" and lazy-load.
<a lazyload="true">
<a lazy-load>

That way I could implement it now without the breaking change.

**Comment by colscott** [comment]
Added lazy-load boolean attribute. lazyload="true" still works but is deprecated and no longer documented.
